context:
  version: "0.4.1"

package:
  name: otree
  version: ${{ version }}

source:
  url: https://github.com/fioncat/otree/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 73bd4aedc7d36621b62baf46e9f2b57f075e183be5baa1bb388ac82f213e452d

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo install --no-track --locked --root ${PREFIX} --path .
          - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
      - if: win
        then:
          - cargo install --no-track --locked --root %PREFIX% --path .
          - if errorlevel 1 exit 1
          - cargo-bundle-licenses --format yaml --output %SRC_DIR%/THIRDPARTY.yml
          - if errorlevel 1 exit 1

requirements:
  build:
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("c") }}
    - cargo-bundle-licenses

tests:
  - script:
      - otree --help

about:
  homepage: https://github.com/fioncat/otree
  repository: https://github.com/fioncat/otree
  documentation: https://github.com/fioncat/otree
  summary: A command line tool to view objects (JSON/YAML/TOML) in TUI tree widget.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - apcamargo
